# Generated by Django 5.0.3 on 2024-04-07 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjects', models.CharField(max_length=100)),
                ('admited', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
