# Generated by Django 5.0.3 on 2024-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
